### ISSUE TITLE
fatal error: runtime: no plugin module data on load

### ISSUE THREAD

**Issue by vadimdoga** [devopsfaith/krakend-ce#328]
**Describe what are you trying to do**
I have a gateway with 3 plugins(http executor) and when I launch the code everything is nice and smooth. I launched this into production and it worked for more or less a month. Couple of days ago I saw that the docker container is in restarting loop. It shows this error `Error: fatal error: runtime: no plugin module data`. I searched for the possible error and tried to replicate it but no success, that's why I am writing here. I can restart and go further but I try to understand why this failure appeared, maybe I missed something during development and this will cause fails every time. 

**Your configuration file**
The content of your `krakend.json`. When using the flexible configuration option, the computed file can be generated using `FC_OUT=out.json`
```
{
    "version": 2,
    "extra_config": {
        "github_com/devopsfaith/krakend-cors": {
            "allow_origins": ["http*"],
            "allow_headers": [
                "Origin",
                "Authorization",
                "Content-Type",
                "Accept",
                "X-Auth-Token"
            ],
            "expose_headers": [
                "Content-Length",
                "Content-Type"
            ],
            "max_age": "12h",
            "allow_credentials": true
        },
        "github_com/devopsfaith/krakend-gologging": {
            "level":  "DEBUG",
            "prefix": "[GATEWAY]",
            "syslog": false,
            "stdout": true
        }
    },
    "timeout": "60s",
    "cache_ttl": "1000s",
    "output_encoding": "json",
    "is_collection": true,
    "name": "classifier-gateway",
    "port": 5051,
    "host": ["classifier:5000"],
    "plugin": {
        "pattern": ".so",
        "folder": "./plugin/"
    },
    "endpoints": [
        {
            "endpoint": "/api/ui",
            "method": "GET",
            "output_encoding": "no-op",
            "backend": [{
                "url_pattern": "/api/v1/ui",
                "encoding": "no-op",
                "extra_config": {
                    "github.com/devopsfaith/krakend/transport/http/client/executor": {
                        "name": "redirect_plugin"
                    }
                }
            }],
            "extra_config": {}
        },
        {
            "endpoint": "/api/v2/documents/{arg}",
            "method": "GET",
            "output_encoding": "no-op",
            "backend": [{
                "url_pattern": "/api/modules?arg={arg}",
                "encoding": "no-op",
                "extra_config": {
                    "github.com/devopsfaith/krakend/transport/http/client/executor": {
                        "name": "get_2_post_plugin",
                        "valid_endpoints": ["Tenders"]
                    }
                }
            }]
        },
        {
            "endpoint": "/api/v2/documents/{arg}/prediction",
            "method": "POST",
            "output_encoding": "no-op",
            "backend": [{
                "url_pattern": "/api/analyze-data?arg={arg}",
                "encoding": "no-op",
                "extra_config":{
                    "github.com/devopsfaith/krakend/transport/http/client/executor": {
                        "name": "validator_plugin",
                        "valid_endpoints": ["Tenders"]
                    }
                }
            }]
        },
        {
            "endpoint": "/api/v2/documents/{arg}/explanation",
            "method": "POST",
            "output_encoding": "no-op",
            "backend": [{
                "url_pattern": "/api/explain-model?arg={arg}",
                "encoding": "no-op",
                "extra_config":{
                    "github.com/devopsfaith/krakend/transport/http/client/executor": {
                        "name": "validator_plugin",
                        "valid_endpoints": ["Tenders"]
                    }
                }
            }]
        },
        {
            "endpoint": "/api/v1/ui",
            "method": "GET",
            "output_encoding": "no-op",
            "backend": [{
                "url_pattern": "/api/ui/",
                "encoding": "no-op"
            }],
            "extra_config": {}
        }
    ]
}

```
**Commands used**
How did you start the software?
```
FROM golang:1.15.8-alpine as builder

WORKDIR /gateway/golang
RUN apk add build-base
COPY plugin/ plugin/
COPY go.mod .

RUN go build -buildmode=plugin -o ./plugin/get_2_post_plugin.so ./plugin/get_2_post_plugin/get_2_post_plugin.go
RUN go build -buildmode=plugin -o ./plugin/redirect_plugin.so ./plugin/redirect_plugin/redirect_plugin.go
RUN go build -buildmode=plugin -o ./plugin/validator_plugin.so ./plugin/validator_plugin/validator_plugin.go

#It was developed when krakend 1.3 version was, but was launched without a version specified, as above
FROM devopsfaith/krakend 

USER root
WORKDIR /etc/krakend/

COPY krakend.json /etc/krakend/krakend.json
COPY --from=builder /classifier_gateway/golang/plugin/*.so /etc/krakend/plugin/

RUN ["/bin/sh", "-c", "mkdir -p /var/lib/apt/lists/partial"]
RUN ["/bin/sh", "-c", "apt-get update && apt-get -y install musl-dev"]
RUN ["/bin/sh", "-c", "ln -s /usr/lib/x86_64-linux-musl/libc.so /lib/libc.musl-x86_64.so.1"]

CMD ["run", "-c", "krakend.json"]

```

**Logs**
If applicable, any logs you saw in the console and debugging information

*Production failure:*
```
Parsing configuration file: krakend.json
[GATEWAY] 2021/07/06 - 08:23:16.198 ▶ ERROR unable to create the GELF writer: getting the extra config for the krakend-gelf module
[GATEWAY] 2021/07/06 - 08:23:16.198 ▶ INFO Listening on port: 5051
fatal error: runtime: no plugin module data

goroutine 1 [running]:
runtime.throw(0x28498dd, 0x1e)
	/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc000bbeee0 sp=0xc000bbeeb0 pc=0xd50712
plugin.lastmoduleinit(0xc000a5a1b0, 0x1001, 0x1001, 0xc0001764f8, 0x7f6ac8000e10)
	/usr/local/go/src/runtime/plugin.go:20 +0xb50 fp=0xc000bbefd8 sp=0xc000bbeee0 pc=0xd836d0
plugin.open(0xc000bf23c0, 0x18, 0x7f6af5771038, 0x38, 0x40)
	/usr/local/go/src/plugin/plugin_dlopen.go:77 +0x4ef fp=0xc000bbf250 sp=0xc000bbefd8 pc=0x10e3a6f
plugin.Open(...)
	/usr/local/go/src/plugin/plugin.go:32
github.com/luraproject/lura/transport/http/client/plugin.defaultPluginOpener(0xc000bf23c0, 0x1b, 0xc000700000, 0x0, 0xc000bbf310, 0xd68a25)
	/go/pkg/mod/github.com/luraproject/lura@v1.4.1/transport/http/client/plugin/plugin.go:115 +0x35 fp=0xc000bbf288 sp=0xc000bbf250 pc=0x1ced115
github.com/luraproject/lura/transport/http/client/plugin.open(0xc000bf23c0, 0x1b, 0x28d4958, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/luraproject/lura@v1.4.1/transport/http/client/plugin/plugin.go:82 +0x7c fp=0xc000bbf308 sp=0xc000bbf288 pc=0x1cece9c
github.com/luraproject/lura/transport/http/client/plugin.load(0xc000bc3400, 0x3, 0x4, 0x28d4958, 0x0, 0x0, 0x4, 0x0, 0x0)
	/go/pkg/mod/github.com/luraproject/lura@v1.4.1/transport/http/client/plugin/plugin.go:57 +0xe5 fp=0xc000bbf3e0 sp=0xc000bbf308 pc=0x1cecb65
github.com/luraproject/lura/transport/http/client/plugin.LoadWithLogger(0xc000bc46f0, 0x9, 0xc000bc46e7, 0x3, 0x28d4958, 0x0, 0x0, 0x30, 0xc000000180, 0x2233c6e)
	/go/pkg/mod/github.com/luraproject/lura@v1.4.1/transport/http/client/plugin/plugin.go:50 +0xcb fp=0xc000bbf438 sp=0xc000bbf3e0 pc=0x1ceca2b
github.com/luraproject/lura/transport/http/client/plugin.Load(...)
	/go/pkg/mod/github.com/luraproject/lura@v1.4.1/transport/http/client/plugin/plugin.go:42
github.com/devopsfaith/krakend-ce.LoadPlugins(0xc000bc46f0, 0x9, 0xc000bc46e7, 0x3, 0x2dfab60, 0xc00026d110)
	/app/plugin.go:11 +0x7b fp=0xc000bbf4c8 sp=0xc000bbf438 pc=0x2233f1b
github.com/devopsfaith/krakend-ce.pluginLoader.Load(...)
	/app/plugin.go:35
github.com/devopsfaith/krakend-ce.(*pluginLoader).Load(0x3c77490, 0xc000bc46f0, 0x9, 0xc000bc46e7, 0x3, 0x2dfab60, 0xc00026d110)
	<autogenerated>:1 +0x6e fp=0xc000bbf508 sp=0xc000bbf4c8 pc=0x2235f2e
github.com/devopsfaith/krakend-ce.(*ExecutorBuilder).NewCmdExecutor.func1(0xc0000529d8, 0x12, 0xc000c96500, 0x13, 0x13, 0xdf8475800, 0xe8d4a51000, 0xc0000b3fb0, 0x1, 0x1, ...)
	/app/executor.go:141 +0x976 fp=0xc000bbf850 sp=0xc000bbf508 pc=0x22355b6
github.com/devopsfaith/krakend-cobra.runFunc(0x3af8a60, 0xc000326d80, 0x0, 0x2)
	/go/pkg/mod/github.com/devopsfaith/krakend-cobra@v1.4.0/run.go:24 +0x1df fp=0xc000bbfbc8 sp=0xc000bbf850 pc=0x1e2941f
github.com/spf13/cobra.(*Command).execute(0x3af8a60, 0xc000326d40, 0x2, 0x2, 0x3af8a60, 0xc000326d40)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2c2 fp=0xc000bbfc88 sp=0xc000bbfbc8 pc=0x1e1bf22
github.com/spf13/cobra.(*Command).ExecuteC(0x3af8560, 0xc00059deb0, 0x28d82f8, 0xc00059deb4)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x30b fp=0xc000bbfd68 sp=0xc000bbfc88 pc=0x1e1cb4b
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/devopsfaith/krakend-cobra.Root.Execute(0x3af8560, 0xc000ac6aa0, 0x2, 0x2, 0xc00059de80, 0xc000910910, 0x2, 0x2, 0xc00059deb0, 0x2dc7560, ...)
	/go/pkg/mod/github.com/devopsfaith/krakend-cobra@v1.4.0/cmd.go:119 +0x69 fp=0xc000bbfdc8 sp=0xc000bbfd68 pc=0x1e287a9
github.com/devopsfaith/krakend-cobra.ExecuteRoot(0x2dc7560, 0xc000c070e0, 0xc000326ce0, 0x3af8560, 0xc000ac6aa0, 0x2, 0x2, 0xc00059de80, 0xc000910910, 0x2, ...)
	/go/pkg/mod/github.com/devopsfaith/krakend-cobra@v1.4.0/cmd.go:26 +0x98 fp=0xc000bbfe38 sp=0xc000bbfdc8 pc=0x1e28138
github.com/devopsfaith/krakend-cobra.Execute(...)
	/go/pkg/mod/github.com/devopsfaith/krakend-cobra@v1.4.0/cmd.go:21
main.main()
	/app/cmd/krakend-ce/main.go:56 +0x3ae fp=0xc000bbff88 sp=0xc000bbfe38 pc=0x22ca84e
runtime.main()
	/usr/local/go/src/runtime/proc.go:225 +0x256 fp=0xc000bbffe0 sp=0xc000bbff88 pc=0xd53196
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000bbffe8 sp=0xc000bbffe0 pc=0xd88e41

goroutine 28 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0001f2c80)
	/go/pkg/mod/go.opencensus.io@v0.22.5/stats/view/worker.go:276 +0xcd
created by go.opencensus.io/stats/view.init.0
	/go/pkg/mod/go.opencensus.io@v0.22.5/stats/view/worker.go:34 +0x68

goroutine 52 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:168 +0xa5
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	/usr/local/go/src/os/signal/signal.go:151 +0x45

goroutine 53 [select]:
main.main.func1(0xc00014acc0, 0xc000ac7bd0, 0x2ded248, 0xc000bc2cc0)
	/app/cmd/krakend-ce/main.go:34 +0xaa
created by main.main
	/app/cmd/krakend-ce/main.go:33 +0x158

goroutine 54 [sleep]:
time.Sleep(0x12a05f200)
	/usr/local/go/src/runtime/time.go:193 +0xd2
github.com/devopsfaith/krakend-ce.startReporter.func1(0x2dfab60, 0xc00026d110, 0xc000175200, 0x2c, 0x2ded248, 0xc000bc2cc0)
	/app/executor.go:314 +0x45
created by github.com/devopsfaith/krakend-ce.startReporter
	/app/executor.go:313 +0x1ee

```

**Comment by kpacha** [comment]
@vadimdoga , just for future references, can you share what was the solution?

**Comment by suadev** [comment]
@vadimdoga hi, I am facing the same issue. 

What was your solution, and what is your go version of your custom go plugins?

Thanks.

**Comment by taik0** [comment]
Usually this error means that you are using plugins compiled for another KrakenD version.
Check that your dependencies and the Go version that you are using matches the required ones for the KrakenD version you are using.
http://plugin-tools.krakend.io/

**Comment by suadev** [comment]
@taik0 thank you for your help.

It looks like my router plugin is loaded successfully. But it doesn't intercept the requests.  

My sample plugin and refined logs are below. 

I have to see the 'auth-plugin called' log for each router request, right?

Thanks in advance!

```go

package main

import (
	"context"
	"errors"
	"fmt"
	"net/http"
)

type registerer string

// HandlerRegisterer is the symbol the plugin loader will try to load. It must implement the Registerer interface
var HandlerRegisterer = registerer("auth-plugin")

func (r registerer) RegisterHandlers(f func(
	name string,
	handler func(context.Context, map[string]interface{}, http.Handler) (http.Handler, error),
)) {
	f(string(r), r.registerHandlers)
}

func (r registerer) registerHandlers(ctx context.Context, extra map[string]interface{}, handler http.Handler) (http.Handler, error) {
	// check the passed configuration and initialize the plugin
	name, ok := extra["name"].([]interface{})
	if !ok {
		return nil, errors.New("wrong config")
	}
	if name[0] != string(r) {
		return nil, fmt.Errorf("unknown register %s", name)
	}

	// return the actual handler wrapping or your custom logic so it can be used as a replacement for the default http handler
	return http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		fmt.Println("auth-plugin called!")
		handler.ServeHTTP(w, req)
	}), nil
}

func init() {
	fmt.Println("auth-plugin handler loaded!")
}

func main() {}
```

Logs:

```js
 "Level": "ERROR", "Message": "unable to create the GELF writer: getting the extra config for the krakend-gelf module", "Timestamp": "2021-07-14T13:16:50.914Z","Program": "krakend" }
{ "Level": "INFO", "Message": "Listening on port: 5000", "Timestamp": "2021-07-14T13:16:50.914Z","Program": "krakend" }
Parsing configuration file: /etc/krakend/config/krakend.json
auth-plugin handler loaded!
{ "Level": "WARNING", "Message": "loading plugins: plugin loader found 1 error(s): 
opening plugin 0 (plugins/auth-plugin.so): plugin: symbol ClientRegisterer not found in plugin router-auth-plugin", "Timestamp": "2021-07-14T13:16:50.927Z","Program": "krakend" }
{ "Level": "INFO", "Message": "total http executor plugins loaded: 0", "Timestamp": "2021-07-14T13:16:50.928Z","Program": "krakend" }
{ "Level": "INFO", "Message": "total http handler plugins loaded: 1", "Timestamp": "2021-07-14T13:16:50.928Z","Program": "krakend" }
```

**Comment by taik0** [comment]
@suadev please, let's move this conversation to the slack channel since it doesn't have to do with this issue.
