### ISSUE TITLE
fatal error: runtime: no plugin module data when trying to load a plugin.

### ISSUE THREAD

**Issue by crisclacerda** [devopsfaith/krakend-ce#415]
**Describe what are you trying to do**
I am trying to follow the [writing plugins docs ](https://www.krakend.io/docs/extending/writing-plugins/) and getting this  [example plugin](https://godoc.org/github.com/devopsfaith/krakend/transport/http/server/plugin) to work on my setup, but I am obviously missing something..

**Your configuration file**

```
{
    "version": 2,
    "plugin": {
        "folder": "/etc/krakend/plugins/",
        "pattern": ".so"
    },
    "extra_config": {
        "github_com/devopsfaith/krakend/transport/http/server/handler": {
            "name": ["krakend-example"]
        }
    },
    "timeout": "3000ms",
    "cache_ttl": "0s",
    "output_encoding": "json",
    "endpoints": [
        {
            "endpoint": "/orders_brief",
            "headers_to_pass": [
                "Content-Type"
                ],
            "backend": [
                {
                    "is_collection": true,
                    "url_pattern": "/orders_brief",
                    "sd": "static",
                    "extra_config": {},
                    "host": [
                        "http://127.0.0.1:3000"
                    ]
                }
            ]
        }
    ]
}

```
**Commands used**
How did you start the software?
```
cd krakend-example && go build -buildmode=plugin -o ../plugins/krakend-example.so plugin.go 
cd .. && krakend run -d -c krakend.json --port 8888 

**Logs**
Parsing configuration file: krakend.json
[KRAKEND] 2022/02/10 - 09:25:19.119 ▶ INFO Listening on port: 8888
fatal error: runtime: no plugin module data

goroutine 1 [running]:
runtime.throw(0x28498dd, 0x1e)
        /usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc00093eee0 sp=0xc00093eeb0 pc=0xd50712
plugin.lastmoduleinit(0xc000621f50, 0x1001, 0x1001, 0xc000134638, 0x7fc904000cf0)
        /usr/local/go/src/runtime/plugin.go:20 +0xb50 fp=0xc00093efd8 sp=0xc00093eee0 pc=0xd836d0
plugin.open(0xc00032ccc0, 0x24, 0x7fc911dd6290, 0x8, 0x10)
        /usr/local/go/src/plugin/plugin_dlopen.go:77 +0x4ef fp=0xc00093f250 sp=0xc00093efd8 pc=0x10e3a6f
plugin.Open(...)
        /usr/local/go/src/plugin/plugin.go:32
github.com/luraproject/lura/transport/http/client/plugin.defaultPluginOpener(0xc00032ccc0, 0x27, 0xc00007c800, 0x0, 0xc00093f310, 0xd68a25)
        /go/pkg/mod/github.com/luraproject/lura@v1.4.1/transport/http/client/plugin/plugin.go:115 +0x35 fp=0xc00093f288 sp=0xc00093f250 pc=0x1ced115
github.com/luraproject/lura/transport/http/client/plugin.open(0xc00032ccc0, 0x27, 0x28d4958, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/luraproject/lura@v1.4.1/transport/http/client/plugin/plugin.go:82 +0x7c fp=0xc00093f308 sp=0xc00093f288 pc=0x1cece9c
github.com/luraproject/lura/transport/http/client/plugin.load(0xc00061a4b0, 0x1, 0x1, 0x28d4958, 0x0, 0x0, 0x1, 0x0, 0x0)
        /go/pkg/mod/github.com/luraproject/lura@v1.4.1/transport/http/client/plugin/plugin.go:57 +0xe5 fp=0xc00093f3e0 sp=0xc00093f308 pc=0x1cecb65
github.com/luraproject/lura/transport/http/client/plugin.LoadWithLogger(0xc000596000, 0x15, 0xc000614217, 0x3, 0x28d4958, 0x0, 0x0, 0x30, 0xc000000180, 0x2233c6e)
        /go/pkg/mod/github.com/luraproject/lura@v1.4.1/transport/http/client/plugin/plugin.go:50 +0xcb fp=0xc00093f438 sp=0xc00093f3e0 pc=0x1ceca2b
github.com/luraproject/lura/transport/http/client/plugin.Load(...)
        /go/pkg/mod/github.com/luraproject/lura@v1.4.1/transport/http/client/plugin/plugin.go:42
github.com/devopsfaith/krakend-ce.LoadPlugins(0xc000596000, 0x15, 0xc000614217, 0x3, 0x2dfab60, 0xc000621650)
        /app/plugin.go:11 +0x7b fp=0xc00093f4c8 sp=0xc00093f438 pc=0x2233f1b
github.com/devopsfaith/krakend-ce.pluginLoader.Load(...)
        /app/plugin.go:35
github.com/devopsfaith/krakend-ce.(*pluginLoader).Load(0x3c77490, 0xc000596000, 0x15, 0xc000614217, 0x3, 0x2dfab60, 0xc000621650)
        <autogenerated>:1 +0x6e fp=0xc00093f508 sp=0xc00093f4c8 pc=0x2235f2e
github.com/devopsfaith/krakend-ce.(*ExecutorBuilder).NewCmdExecutor.func1(0xc000614320, 0xd, 0xc0001343e8, 0x1, 0x1, 0xb2d05e00, 0x0, 0x3c77490, 0x0, 0x0, ...)
        /app/executor.go:141 +0x976 fp=0xc00093f850 sp=0xc00093f508 pc=0x22355b6
github.com/devopsfaith/krakend-cobra.runFunc(0x3af8a60, 0xc00061e3c0, 0x0, 0x5)
        /go/pkg/mod/github.com/devopsfaith/krakend-cobra@v1.4.0/run.go:24 +0x1df fp=0xc00093fbc8 sp=0xc00093f850 pc=0x1e2941f
github.com/spf13/cobra.(*Command).execute(0x3af8a60, 0xc00061e370, 0x5, 0x5, 0x3af8a60, 0xc00061e370)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2c2 fp=0xc00093fc88 sp=0xc00093fbc8 pc=0x1e1bf22
github.com/spf13/cobra.(*Command).ExecuteC(0x3af8560, 0xc0008488d0, 0x28d82f8, 0xc0008488d4)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x30b fp=0xc00093fd68 sp=0xc00093fc88 pc=0x1e1cb4b
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/devopsfaith/krakend-cobra.Root.Execute(0x3af8560, 0xc00071b750, 0x2, 0x2, 0xc0008488a0, 0xc0007416d0, 0x2, 0x2, 0xc0008488d0, 0x2dc7560, ...)
        /go/pkg/mod/github.com/devopsfaith/krakend-cobra@v1.4.0/cmd.go:119 +0x69 fp=0xc00093fdc8 sp=0xc00093fd68 pc=0x1e287a9
github.com/devopsfaith/krakend-cobra.ExecuteRoot(0x2dc7560, 0xc0004fc480, 0xc000522000, 0x3af8560, 0xc00071b750, 0x2, 0x2, 0xc0008488a0, 0xc0007416d0, 0x2, ...)
        /go/pkg/mod/github.com/devopsfaith/krakend-cobra@v1.4.0/cmd.go:26 +0x98 fp=0xc00093fe38 sp=0xc00093fdc8 pc=0x1e28138
github.com/devopsfaith/krakend-cobra.Execute(...)
        /go/pkg/mod/github.com/devopsfaith/krakend-cobra@v1.4.0/cmd.go:21
main.main()
        /app/cmd/krakend-ce/main.go:56 +0x3ae fp=0xc00093ff88 sp=0xc00093fe38 pc=0x22ca84e
runtime.main()
        /usr/local/go/src/runtime/proc.go:225 +0x256 fp=0xc00093ffe0 sp=0xc00093ff88 pc=0xd53196
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc00093ffe8 sp=0xc00093ffe0 pc=0xd88e41

goroutine 36 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000240980)
        /go/pkg/mod/go.opencensus.io@v0.22.5/stats/view/worker.go:276 +0xcd
created by go.opencensus.io/stats/view.init.0
        /go/pkg/mod/go.opencensus.io@v0.22.5/stats/view/worker.go:34 +0x68

goroutine 21 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:168 +0xa5
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
        /usr/local/go/src/os/signal/signal.go:151 +0x45

goroutine 22 [select]:
main.main.func1(0xc000136f60, 0xc0004f4040, 0x2ded248, 0xc00075e000)
        /app/cmd/krakend-ce/main.go:34 +0xaa
created by main.main
        /app/cmd/krakend-ce/main.go:33 +0x158

goroutine 23 [sleep]:
time.Sleep(0x12a05f200)
        /usr/local/go/src/runtime/time.go:193 +0xd2
github.com/devopsfaith/krakend-ce.startReporter.func1(0x2dfab60, 0xc000621650, 0xc00032cbd0, 0x2c, 0x2ded248, 0xc00075e000)
        /app/executor.go:314 +0x45
created by github.com/devopsfaith/krakend-ce.startReporter
        /app/executor.go:313 +0x1ee

**Comment by kpacha** [comment]
Quick suggestions:
1. create a go module for each plugin `go mod init <your_plugin_mod_name>`
2. compile the entire plugin by replacing you command with: `go build -buildmode=plugin -o ../plugins/krakend-example.so .`

The error you're facing is thrown by the stdlib: https://cs.opensource.google/go/go/+/refs/tags/go1.17.6:src/runtime/plugin.go;l=11-21
