### ISSUE TITLE
'Index out of Range' after Upgrade to KrakenD 2.0

### ISSUE THREAD

**Issue by moritzploss-k** [devopsfaith/krakend-ce#479]
**Describe the bug**
After upgrading to KrakenD 2.0, we have seen the following error when starting KrakenD and running `krakend check`. The error is not 100 % reproducible; for the config file below it occurs maybe one out of ten times. We have found that the error becomes more reproducible if we increase the number of endpoints in the config.

**Your configuration file**
Uploaded [here](https://github.com/devopsfaith/krakend-ce/files/8479954/out.txt). Used .txt extension since GitHub doesn't allow .json.

**Commands used**

```
docker run --rm \
  -v "${PWD}/out.txt:/etc/krakend/config/krakend.json" \
  devopsfaith/krakend:latest check -t -c ./config/krakend.json
```
**Expected behavior**
Should not crash.

**Logs**

Error log:

```
Parsing configuration file: ./config/krakend.json
panic: runtime error: index out of range [9] with length 9

goroutine 14 [running]:
github.com/gin-gonic/gin.(*node).incrementChildPrio(0x22fd5a0, 0xc000276140)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/tree.go:130 +0x18d
github.com/gin-gonic/gin.(*node).addRoute(0xc00090e0e0, {0xc000884144, 0x2}, {0xc00065d2a8, 0x3, 0x3})
        /go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/tree.go:224 +0x9e5
github.com/gin-gonic/gin.(*Engine).addRoute(0xc000102820, {0x2459cb0, 0xc0005b76f4}, {0xc000884144, 0x2}, {0xc00065d2a8, 0x3, 0x3})
        /go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:305 +0x1fa
github.com/gin-gonic/gin.(*RouterGroup).handle(0xc0001d21c0, {0x2459cb0, 0x3}, {0xc0005b76f4, 0xc00074a640}, {0xc0001a62f8, 0x1, 0xc0005b76f4})
        /go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/routergroup.go:75 +0x145
github.com/gin-gonic/gin.(*RouterGroup).GET(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/routergroup.go:103
github.com/luraproject/lura/v2/router/gin.ginRouter.registerKrakendEndpoint({{0xc000102820, {0x3ab80f0, 0x0, 0x0}, 0xc000504ec0, {0x2a64f20, 0xc0003bb780}, {0x2a9bff8, 0xc0003bb7a0}, 0x2565dd8}, ...}, ...)
        /go/pkg/mod/github.com/luraproject/lura/v2@v2.0.1/router/gin/router.go:185 +0x265
github.com/luraproject/lura/v2/router/gin.ginRouter.registerKrakendEndpoints.func1()
        /go/pkg/mod/github.com/luraproject/lura/v2@v2.0.1/router/gin/router.go:165 +0x1b0
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x92
```

**Comment by lodgify-daniel** [comment]
Hello, 
we also found this error in the `check` after upgrading to 2.0.
Cheers

**Comment by kpacha** [comment]
try adding `"sequential_start":true` to your krakend configuration. It should stop these race conditions

**Comment by lodgify-daniel** [comment]
Thanks @kpacha !

**Comment by moritzploss-k** [comment]
Thanks @kpacha! That works!
